version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
    resource_class: large
  deploy:
    docker:
      - image: circleci/node:16.10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          command: npm run deploy
          environment:
            NODE_OPTIONS: --max_old_space_size=4096
    resource_class: large

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
  pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
