'use strict'

export { default as DarkAngels } from './dark-angels'
export { default as EmperorsChildren } from './emperors-children'
export { default as IronWarriors } from './iron-warriors'
export { default as WhiteScars } from './white-scars'
export { default as ImperialFists } from './imperial-fists'
export { default as SpaceWolves } from './space-wolves'
export { default as NightLords } from './night-lords'
export { default as BloodAngels } from './blood-angels'
export { default as IronHands } from './iron-hands'
export { default as WorldEaters } from './world-eaters'
export { default as Ultramarines } from './ultramarines'
export { default as DeathGuard } from './death-guard'
export { default as ThousandSons } from './thousand-sons'
export { default as SonsOfHorus } from './sons-of-horus'
export { default as WordBearers } from './word-bearers'
export { default as Salamanders } from './salamanders'
export { default as RavenGuard } from './raven-guard'
export { default as AlphaLegion } from './alpha-legion'

export { default as LegioCustodes } from './legio-custodes'
export { default as ImperialMilitia } from './imperial-militia'
export { default as LegioTitanicus } from './legio-titanicus'
export { default as MechanicumTaghmata } from './mechanicum-taghmata'
export { default as KnightHousehold } from './knight-household'
export { default as SolarAuxilia } from './solar-auxilia'
export { default as DaemonicHordes } from './daemonic-hordes'
